---
title: "analyse"
author: "Stephan Walker"
format: html
editor: visual
lang: de
---

# Einleitung

```{r}
library(tidyverse)
```

# Daten

Import

```{r}
input_data <- read_csv(here::here("daten/processed/cortison_tidy.csv"))

glimpse(input_data)
```

## Bestimmungsgrenze

Werte unterhalbder Bestimmungsgrenze können zwischen 0 und der Bestimmungsgrenze liegen. Für Methode ACN 1 µg/kg, für Methode EtAc 0.25 µg/kg

```{r}
ohne_NA <- input_data |> 
  mutate(cortison_low = case_when(
    cortison_conc = is.na(cortison_conc) ~ 0,
    .default = cortison_conc
  )) |> 
  mutate(bg = case_when(
    methode == "EtAc" ~ 0.25,
    methode == "ACN"~ 1
  )) |> 
  mutate(cortison_bg = case_when(
    cortison_low == "0" ~ bg,
    .default = cortison_low
  )) |> 
  mutate(hydrocortison_low = case_when(
    hydrocortison_conc = is.na(hydrocortison_conc) ~ 0,
    .default = hydrocortison_conc
  )) |> 
  mutate(hydrocortison_bg = case_when(
    hydrocortison_low == "0" ~ bg,
    .default = hydrocortison_low
  ))
    
  
glimpse(ohne_NA)
ohne_NA |> 
  count(bg)

ohne_NA |> 
  count(matrix)
```

Nur feste Proben

```{r}
feste_matrix <- ohne_NA |> 
  filter(matrix == "Muskel" | matrix == "Leber" | matrix == "Niere" )
```

Nur Muskel

```{r}
muskel <- ohne_NA |> 
  filter(matrix == "Muskel")
```

Anazhl Proben

```{r}
ohne_NA |> 
  count(matrix) |> 
  gt()

```

# Auswertung

low bound, high bound

```{r}
ohne_NA |> 
  group_by(matrix) |> 
  summarise(round(mean(cortison_low),2), 
            round(mean(cortison_bg),2), 
            round(mean(hydrocortison_low),2),
            round(mean(hydrocortison_bg),2))|> 
  gt()

```

Matrix Kennzahlen

```{r}
ohne_NA |> 
  group_by(matrix) |> 
  summarise(n(),
            round(min(cortison_low),0),
            round(mean(cortison_low),0),
            round(max(cortison_low),0)) |> 
  gt()

ohne_NA |> 
  group_by(matrix) |> 
  summarise(n(),
            round(min(hydrocortison_low),0),
            round(mean(hydrocortison_low),0),
            round(max(hydrocortison_low),0)) |> 
  gt()
```

```{r}
ggplot(feste_matrix, mapping = aes(x = hydrocortison_low))+
  geom_histogram()+
  facet_wrap(~matrix)
```

```{r}
ggplot(feste_matrix, mapping = aes(x = tierart,
                              y = hydrocortison_low))+
  geom_boxplot()+
  facet_grid(matrix ~ .)
```

```{r}
ggplot(feste_matrix, mapping = aes(x = matrix,
                                   y = hydrocortison_low))+
  geom_boxplot(outlier.shape = NA)+
  facet_wrap(~tierart)+
  theme_minimal()

```
